<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Category;
use App\Models\Product;

class LocalDataSeeder extends Seeder
{
    public function run(): void
    {
        // \Illuminate\Support\Facades\DB::statement('SET CONSTRAINTS ALL DEFERRED'); // Para Postgres
        // Si es MySQL: \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();

        $categories = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Consolas',
    'slug' => 'consolas',
    'description' => 'Las mejores consolas de videojuegos',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'Videojuegos',
    'slug' => 'videojuegos',
    'description' => 'Todos los juegos para tus plataformas favoritas',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
  2 => 
  array (
    'id' => 3,
    'name' => 'Manga',
    'slug' => 'manga',
    'description' => 'C├│mics y novelas gr├íficas japonesas',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
  3 => 
  array (
    'id' => 4,
    'name' => 'Productos Anime',
    'slug' => 'productos-anime',
    'description' => 'Figuras, accesorios y merchandising de tus animes favoritos',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
  4 => 
  array (
    'id' => 5,
    'name' => 'Cosplay',
    'slug' => 'cosplay',
    'description' => 'Disfraces y accesorios para cosplay',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
  5 => 
  array (
    'id' => 6,
    'name' => 'Productos',
    'slug' => 'productos',
    'description' => 'Todo tipo de productos relacionados con el mundo gamer',
    'iva' => 21,
    'image' => NULL,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
  ),
);
        foreach ($categories as $cat) {
            Category::updateOrCreate(['id' => $cat['id']], $cat);
        }
        $this->command->info('✅ Categorías migradas.');

        $users = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Daniel',
    'email' => 'danielsmartin2005@gmail.com',
    'avatar' => NULL,
    'is_admin' => true,
    'is_super_admin' => 1,
    'auction_notifications' => NULL,
    'email_verified_at' => '2026-03-05T19:37:05.000000Z',
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:40:25.000000Z',
    'avatar_url' => 'https://ui-avatars.com/api/?name=Daniel&background=0D8ABC&color=fff',
  ),
  1 => 
  array (
    'id' => 3,
    'name' => 'Luigi',
    'email' => 'luigi@gmail.com',
    'avatar' => NULL,
    'is_admin' => false,
    'is_super_admin' => 0,
    'auction_notifications' => NULL,
    'email_verified_at' => NULL,
    'created_at' => '2026-03-05T19:53:04.000000Z',
    'updated_at' => '2026-03-05T19:53:48.000000Z',
    'avatar_url' => 'https://ui-avatars.com/api/?name=Luigi&background=0D8ABC&color=fff',
  ),
  2 => 
  array (
    'id' => 4,
    'name' => 'Test User',
    'email' => 'test@example.com',
    'avatar' => NULL,
    'is_admin' => false,
    'is_super_admin' => 0,
    'auction_notifications' => NULL,
    'email_verified_at' => NULL,
    'created_at' => '2026-03-15T18:24:54.000000Z',
    'updated_at' => '2026-03-15T18:24:54.000000Z',
    'avatar_url' => 'https://ui-avatars.com/api/?name=Test+User&background=0D8ABC&color=fff',
  ),
);
        foreach ($users as $u) {
            User::updateOrCreate(['id' => $u['id']], $u);
        }
        $this->command->info('✅ Usuarios migrados.');

        $products = array (
  0 => 
  array (
    'id' => 1,
    'category_id' => 1,
    'name' => 'PlayStation 5',
    'slug' => 'ps5',
    'description' => 'La consola de nueva generaci├│n con gr├íficos 4K y SSD ultrarr├ípido',
    'price' => '499.99',
    'original_price' => NULL,
    'stock' => 10,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'products/BsmPPxDP2CPVHohHzf2tIUTL8ZqzNbpYsdDkWdqB.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-15T16:53:57.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'http://localhost:8000/storage/products/BsmPPxDP2CPVHohHzf2tIUTL8ZqzNbpYsdDkWdqB.jpg',
  ),
  1 => 
  array (
    'id' => 2,
    'category_id' => 1,
    'name' => 'Nintendo Switch OLED',
    'slug' => 'switch-oled',
    'description' => 'La consola h├¡brida con pantalla OLED de 7 pulgadas',
    'price' => '339.99',
    'original_price' => '399.99',
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSNQUxZEb2QMrQoU3tCjDU3DVBGY1IivMQITShZ2BnGfeM29MPCvAPZbiBbusvJD4Nxp5nxtMlfbRtmncXPEmXCh7pDkP9YeTD2FyJTiA44W4q6OHoXGRzp0baxfb7o0RJaZAF4jw&usqp=CAc',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSNQUxZEb2QMrQoU3tCjDU3DVBGY1IivMQITShZ2BnGfeM29MPCvAPZbiBbusvJD4Nxp5nxtMlfbRtmncXPEmXCh7pDkP9YeTD2FyJTiA44W4q6OHoXGRzp0baxfb7o0RJaZAF4jw&usqp=CAc',
  ),
  2 => 
  array (
    'id' => 3,
    'category_id' => 1,
    'name' => 'Nintendo Switch Hyrule Edition',
    'slug' => 'switch-hyrule',
    'description' => 'Edici├│n especial de The Legend of Zelda. Consola con dise├▒o de Hyrule, dock decorado y funda exclusiva. Incluye el juego Tears of the Kingdom.',
    'price' => '243.00',
    'original_price' => NULL,
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://img.pccomponentes.com/articles/1084/10843258/1913-nintendo-switch-lite-hyrule-edition-12-meses-nintendo-switch-online-caracteristicas.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:43:13.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => true,
    'auction_final_price' => NULL,
    'image_url' => 'https://img.pccomponentes.com/articles/1084/10843258/1913-nintendo-switch-lite-hyrule-edition-12-meses-nintendo-switch-online-caracteristicas.jpg',
  ),
  3 => 
  array (
    'id' => 4,
    'category_id' => 1,
    'name' => 'PlayStation 5 Edici├│n 30 Aniversario',
    'slug' => 'ps5-30aniversario',
    'description' => 'Edici├│n limitada del 30 aniversario de PlayStation. Incluye consola con dise├▒os exclusivos, mando especial y placa conmemorativa.',
    'price' => '850.00',
    'original_price' => '900.00',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://i.ytimg.com/vi/BWr2P9Udz7M/maxresdefault.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:16.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://i.ytimg.com/vi/BWr2P9Udz7M/maxresdefault.jpg',
  ),
  4 => 
  array (
    'id' => 5,
    'category_id' => 2,
    'name' => 'Elden Ring',
    'slug' => 'elden-ring',
    'description' => 'Juego del a├▒o. Edici├│n est├índar.',
    'price' => '59.49',
    'original_price' => '69.99',
    'stock' => 9,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://periodismo.ull.es/wp-content/uploads/2022/04/Se-rumorea-que-Elden-Ring-realizara-proximamente-una-nueva-prueba.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:45:29.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://periodismo.ull.es/wp-content/uploads/2022/04/Se-rumorea-que-Elden-Ring-realizara-proximamente-una-nueva-prueba.jpg',
  ),
  5 => 
  array (
    'id' => 6,
    'category_id' => 2,
    'name' => 'Final Fantasy VII Rebirth',
    'slug' => 'ff7-rebirth',
    'description' => 'La esperada continuaci├│n.',
    'price' => '69.99',
    'original_price' => NULL,
    'stock' => 50,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://cdn1.epicgames.com/offer/e9a679451d094c1ba3d008b6a01adec5/EGS_FINALFANTASYVIIREBIRTH_SquareEnix_S1_2560x1440-e254f978084058f898118dc49728d04c',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://cdn1.epicgames.com/offer/e9a679451d094c1ba3d008b6a01adec5/EGS_FINALFANTASYVIIREBIRTH_SquareEnix_S1_2560x1440-e254f978084058f898118dc49728d04c',
  ),
  6 => 
  array (
    'id' => 7,
    'category_id' => 2,
    'name' => 'Super Mario Galaxy 1 + 2',
    'slug' => 'mario-galaxy',
    'description' => 'Los dos juegos de las mejores sagas de Super Mario',
    'price' => '69.99',
    'original_price' => NULL,
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://m.media-amazon.com/images/I/810UZa3-MpL._UF1000,1000_QL80_.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://m.media-amazon.com/images/I/810UZa3-MpL._UF1000,1000_QL80_.jpg',
  ),
  7 => 
  array (
    'id' => 8,
    'category_id' => 3,
    'name' => 'Dragon Ball Box Set',
    'slug' => 'dragon-ball-z-box',
    'description' => 'Colecci├│n completa tomos 1-42 del manga de Dragon Ball original',
    'price' => '200.00',
    'original_price' => '239.99',
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://jumpichiban.com/cdn/shop/files/DragonBall-Complete42VolumeSetDoubleCoverBox_JumpComics_3.jpg?v=1746966724&width=1000',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:21.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://jumpichiban.com/cdn/shop/files/DragonBall-Complete42VolumeSetDoubleCoverBox_JumpComics_3.jpg?v=1746966724&width=1000',
  ),
  8 => 
  array (
    'id' => 9,
    'category_id' => 3,
    'name' => 'Berserk Deluxe Edition Vol. 1-7',
    'slug' => 'berserk-deluxe',
    'description' => 'Colecci├│n de lujo de Berserk. Incluye los primeros 7 vol├║menes en formato gigante, con ilustraciones a color y cubiertas de tela.',
    'price' => '220.00',
    'original_price' => '253.00',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://m.media-amazon.com/images/I/917hnLqEpTL._AC_UF1000,1000_QL80_.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:27.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://m.media-amazon.com/images/I/917hnLqEpTL._AC_UF1000,1000_QL80_.jpg',
  ),
  9 => 
  array (
    'id' => 10,
    'category_id' => 3,
    'name' => '10 tomos de Inazuma Eleven',
    'slug' => 'inazuma',
    'description' => '10 tomos completos de Inazuma Eleven el mejor anime/manga de f├║tbol, Blue lock es una mierda',
    'price' => '70.00',
    'original_price' => '85.00',
    'stock' => 10,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://www.hit-japan.com/book24/190405020.JPG',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://www.hit-japan.com/book24/190405020.JPG',
  ),
  10 => 
  array (
    'id' => 11,
    'category_id' => 3,
    'name' => 'Pack Manga Starter Set Super Mario Volumen 1 a 3',
    'slug' => 'mario-manga',
    'description' => 'Tres tomos del manga de Super Mario',
    'price' => '20.00',
    'original_price' => '25.00',
    'stock' => 10,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://kurogami.com/med/img/productos/35/20/portada-del-pack-manga-super-mario.png',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://kurogami.com/med/img/productos/35/20/portada-del-pack-manga-super-mario.png',
  ),
  11 => 
  array (
    'id' => 12,
    'category_id' => 4,
    'name' => 'Figura Goku SSJ',
    'slug' => 'goku-ssj',
    'description' => 'Figura detallada de 20cm de la famosa escena de la primera vez que se transforma Goku en SSJ',
    'price' => '90.00',
    'original_price' => NULL,
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://www.raccoongames.es/img/productos/2020/11/25/dragon-ball-z-goku-ss-diorama-the-brush-overseas-super-master-stars-piece-banpresto%201.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://www.raccoongames.es/img/productos/2020/11/25/dragon-ball-z-goku-ss-diorama-the-brush-overseas-super-master-stars-piece-banpresto%201.jpg',
  ),
  12 => 
  array (
    'id' => 13,
    'category_id' => 4,
    'name' => 'Figura de Naruto modo Sabio',
    'slug' => 'naruto-sabio',
    'description' => 'Figura de Naruto de 22cm en su estado Sabio',
    'price' => '70.00',
    'original_price' => NULL,
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://comicstores.es/imagenes_grandes/4983164/498316428940.JPG',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://comicstores.es/imagenes_grandes/4983164/498316428940.JPG',
  ),
  13 => 
  array (
    'id' => 14,
    'category_id' => 4,
    'name' => 'Taza T├®rmica de JJK',
    'slug' => 'taza-anime-jjk',
    'description' => 'Taza con dise├▒o de Itadori y Sukuna, capacidad 350ml',
    'price' => '13.00',
    'original_price' => NULL,
    'stock' => 15,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRx24t0g1HGcuHk3JrlyB2WYXvsz47TaVpMEcOCPnhimcDV3HR7yPiWIGSlIbXFwvwlppIsljXYQCROG1kgFCpMpKgEA5wRCkLqhXOFNqDP4sh86iRVaSO15l_TkTSpwLdtUuuLG_5-fg&usqp=CAc',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRx24t0g1HGcuHk3JrlyB2WYXvsz47TaVpMEcOCPnhimcDV3HR7yPiWIGSlIbXFwvwlppIsljXYQCROG1kgFCpMpKgEA5wRCkLqhXOFNqDP4sh86iRVaSO15l_TkTSpwLdtUuuLG_5-fg&usqp=CAc',
  ),
  14 => 
  array (
    'id' => 15,
    'category_id' => 4,
    'name' => 'Llavero Surtido de Danger in my Heart',
    'slug' => 'llavero-anime-danger',
    'description' => 'Llaveros de los personajes de Ichikawa y Yamada del anime Danger in my Heart',
    'price' => '3.59',
    'original_price' => NULL,
    'stock' => 30,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://ae01.alicdn.com/kf/S09b5357451c343f58e66de13b8cb8c02Y.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://ae01.alicdn.com/kf/S09b5357451c343f58e66de13b8cb8c02Y.jpg',
  ),
  15 => 
  array (
    'id' => 16,
    'category_id' => 4,
    'name' => 'Figura Goku Ultra Instinct - Masterlise',
    'slug' => 'goku-masterlise',
    'description' => 'Figura de edici├│n limitada de 33cm. M├íxima calidad, con base numerada y certificado de autenticidad. Importada directamente de Jap├│n.',
    'price' => '70.00',
    'original_price' => '80.00',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://tienda-dragon-ball.com/wp-content/uploads/2024/08/figura-de-goku-ultra-instinto-1.webp',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:32.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://tienda-dragon-ball.com/wp-content/uploads/2024/08/figura-de-goku-ultra-instinto-1.webp',
  ),
  16 => 
  array (
    'id' => 17,
    'category_id' => 4,
    'name' => 'Figura de Ichikawa y Yamada',
    'slug' => 'figura-ichikawa-yamada',
    'description' => 'Figura de Ichikawa y Yamada de uno de los momentos mas emotivos del anime',
    'price' => '50.00',
    'original_price' => '60.00',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhWMXtqfWCVfSoVGDKn8gjm08qEyZZLB_62-jwzCA8G3r5_mPEvtXLXFmhSGLivbbM5ZR2cmjtcFfmnYXJBp_gTk-WDEIG6KavB7FZ67_MBmt57BMwjZIgjTfXYw-GxTzSr2TEmq0yydkt8/s16000-rw/27.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:36.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhWMXtqfWCVfSoVGDKn8gjm08qEyZZLB_62-jwzCA8G3r5_mPEvtXLXFmhSGLivbbM5ZR2cmjtcFfmnYXJBp_gTk-WDEIG6KavB7FZ67_MBmt57BMwjZIgjTfXYw-GxTzSr2TEmq0yydkt8/s16000-rw/27.jpg',
  ),
  17 => 
  array (
    'id' => 18,
    'category_id' => 4,
    'name' => 'Figura Eren Jaeger',
    'slug' => 'eren',
    'description' => 'Figura coleccionable de Attack on Titan de Eren Jaegar de 90cm.',
    'price' => '800.00',
    'original_price' => '860.00',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://yardratshop.com/wp-content/uploads/2025/04/eren-jaeger-diorama-hertz-studio-attack-on-titan4.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:42.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://yardratshop.com/wp-content/uploads/2025/04/eren-jaeger-diorama-hertz-studio-attack-on-titan4.jpg',
  ),
  18 => 
  array (
    'id' => 19,
    'category_id' => 5,
    'name' => 'Cosplay Anna Yamada',
    'slug' => 'annayamada-cosplay',
    'description' => 'Disfraz oficial de Anna Yamada del anime "Boku no Kokoro no Yabai Yatsu"',
    'price' => '89.99',
    'original_price' => NULL,
    'stock' => 3,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://i.redd.it/my-anna-yamada-cosplay-from-the-dangers-in-my-heart-v0-7r1cex3e94re1.jpg?width=2316&format=pjpg&auto=webp&s=377119061f21d14b352b460166e3d5df9bad4ff7',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://i.redd.it/my-anna-yamada-cosplay-from-the-dangers-in-my-heart-v0-7r1cex3e94re1.jpg?width=2316&format=pjpg&auto=webp&s=377119061f21d14b352b460166e3d5df9bad4ff7',
  ),
  19 => 
  array (
    'id' => 20,
    'category_id' => 5,
    'name' => 'Cosplay Armadura de Guts (Berserk)',
    'slug' => 'cosplay-guts',
    'description' => 'Disfraz profesional de Guts. Incluye armadura de imitaci├│n metal, capa, espada Dragon Slayer y peluca. Hecho a medida bajo pedido.',
    'price' => '299.99',
    'original_price' => '349.99',
    'stock' => 1,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://i.redd.it/wi6l7goktixa1.jpg',
    'is_featured' => 0,
    'is_exclusive' => true,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:41:47.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://i.redd.it/wi6l7goktixa1.jpg',
  ),
  20 => 
  array (
    'id' => 21,
    'category_id' => 5,
    'name' => 'Cosplay zero two',
    'slug' => 'zero-two',
    'description' => 'Cosplay de zero two del anime de Darling in the Franx',
    'price' => '100.00',
    'original_price' => NULL,
    'stock' => 3,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://i.pinimg.com/736x/bc/a3/80/bca380011a5a682a9e7766c1d7c2db82.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://i.pinimg.com/736x/bc/a3/80/bca380011a5a682a9e7766c1d7c2db82.jpg',
  ),
  21 => 
  array (
    'id' => 22,
    'category_id' => 5,
    'name' => 'Cosplay de Igris',
    'slug' => 'igris',
    'description' => 'Cosplay de Igris una de las sombras mas fuertes de Sung Jin-Woo de Solo Leveling',
    'price' => '200.00',
    'original_price' => '250.00',
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://i.redd.it/my-blood-red-commander-igris-cosplay-game-version-v0-zrx40f3kpcrc1.jpg?width=4016&format=pjpg&auto=webp&s=8665949fe51b172e02ec01b74f059a0cc460cbcf',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://i.redd.it/my-blood-red-commander-igris-cosplay-game-version-v0-zrx40f3kpcrc1.jpg?width=4016&format=pjpg&auto=webp&s=8665949fe51b172e02ec01b74f059a0cc460cbcf',
  ),
  22 => 
  array (
    'id' => 23,
    'category_id' => 5,
    'name' => 'Cosplay de Luigi',
    'slug' => 'cosplay-luigi',
    'description' => 'Cosplay de Luigi version realista del fontanero',
    'price' => '45.00',
    'original_price' => '50.00',
    'stock' => 5,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => false,
    'specs' => NULL,
    'image' => 'https://raw.githubusercontent.com/Daniel2005-32/Beta-Proyecto-final/main/unnamed.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://raw.githubusercontent.com/Daniel2005-32/Beta-Proyecto-final/main/unnamed.jpg',
  ),
  23 => 
  array (
    'id' => 24,
    'category_id' => 6,
    'name' => 'Peluche de Luigi',
    'slug' => 'peluche-luigi',
    'description' => 'Peluche Luigi 30cm Super Mario Bros Nintendo',
    'price' => '20.00',
    'original_price' => NULL,
    'stock' => 20,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => true,
    'trending' => true,
    'specs' => NULL,
    'image' => 'https://dam.elcorteingles.es/producto/www-001008341136573-00.jpg?impolicy=Resize&width=1200&height=1200',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-05T19:37:05.000000Z',
    'updated_at' => '2026-03-05T19:37:05.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'https://dam.elcorteingles.es/producto/www-001008341136573-00.jpg?impolicy=Resize&width=1200&height=1200',
  ),
  24 => 
  array (
    'id' => 25,
    'category_id' => 5,
    'name' => 'Sukuna',
    'slug' => 'sukuna-69b6e3498dfb2',
    'description' => 'Sukuna',
    'price' => '52.00',
    'original_price' => '66.00',
    'stock' => 4,
    'is_in_auction' => false,
    'auction_start_price' => NULL,
    'auction_end_time' => NULL,
    'featured' => false,
    'trending' => false,
    'specs' => NULL,
    'image' => 'products/rIZuHTIcK55PCafGRuN9g80xWR3nc5KNpvr1DqvE.jpg',
    'is_featured' => 0,
    'is_exclusive' => false,
    'is_trend' => 0,
    'created_at' => '2026-03-15T16:50:17.000000Z',
    'updated_at' => '2026-03-15T18:51:52.000000Z',
    'auction_winner_id' => NULL,
    'auction_claimed' => false,
    'auction_cancelled' => false,
    'auction_final_price' => NULL,
    'image_url' => 'http://localhost:8000/storage/products/rIZuHTIcK55PCafGRuN9g80xWR3nc5KNpvr1DqvE.jpg',
  ),
);
        foreach ($products as $p) {
            Product::updateOrCreate(['id' => $p['id']], $p);
        }
        $this->command->info('✅ Productos migrados.');

    }
}
